{% set name = "adam_core" %}
{% set version = "0.5.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adam_core-{{ version }}.tar.gz
  sha256: 27c10c0bad590f856e680a98b59f9887d0d2e4bf78a398086b4f7aefbe2ce04e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - astroquery
    - healpy
    - jax
    - jaxlib
    - numba
    - numpy >=2.0.0
    - pdm
    - pyarrow >=13.0.0
    - pandas
    - ray-core
    - requests
    - scipy
    - spiceypy
    - quivr >=0.7.5
    - mpc-obscodes
    - naif_de440
    - naif_leapseconds
    - naif_eop_high_prec
    - naif_eop_predict
    - naif_eop_historical
    - naif_earth_itrf93
    - timezonefinder

test:
  imports:
    - adam_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Core libraries for the ADAM platform
  home: https://github.com/B612-Asteroid-Institute/adam_core
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - akoumjian
    - moeyensj
    - ntellis
    - KatKiker
